package com.fhtechnikum.paperless.services.mapper;

import com.fhtechnikum.paperless.persistence.entity.DocumentEntity;
import com.fhtechnikum.paperless.persistence.entity.NoteEntity;
import com.fhtechnikum.paperless.services.dto.Note;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

import static org.junit.jupiter.api.Assertions.*;

class NoteMapperTest {

    private final NoteMapper mapper = new NoteMapperImpl();

    @Test
    void toDto_ShouldMapFieldsAndExtractDocumentId() {

        DocumentEntity doc = new DocumentEntity();
        doc.setId(99L);

        NoteEntity entity = new NoteEntity();
        entity.setId(1L);
        entity.setContent("Test Note Content");
        entity.setDocument(doc); // Set the relationship
        entity.setCreatedDate(LocalDateTime.now());

        Note dto = mapper.toDto(entity);

        assertNotNull(dto);
        assertEquals(1L, dto.getId());
        assertEquals("Test Note Content", dto.getContent());
        assertEquals(99L, dto.getDocumentId(), "Should extract the ID from the DocumentEntity");
    }

    @Test
    void toEntity_ShouldMapContentAndIgnoreRest() {

        Note dto = new Note();
        dto.setContent("New content from API");

        // should be ignored
        dto.setId(50L);
        dto.setDocumentId(50L);

        NoteEntity entity = mapper.toEntity(dto);

        assertNotNull(entity);
        assertEquals("New content from API", entity.getContent());
        assertNull(entity.getId(), "ID should be ignored (generated by DB)");
        assertNull(entity.getDocument(), "Document should be ignored (set by service)");
    }

    @Test
    void fromLocalDateTime_ShouldConvertToUtc() {

        LocalDateTime local = LocalDateTime.of(2024, 1, 1, 12, 0);

        OffsetDateTime result = mapper.fromLocalDateTime(local);

        assertNotNull(result);
        assertEquals(ZoneOffset.UTC, result.getOffset());
        assertEquals(2024, result.getYear());
    }
}